<?php
require '../config/config.php';
require '../includes/fpdf.php';

class PDF extends FPDF {
    // Header with logo and title
    function Header() {
        // Background color for the top section
        $this->SetFillColor(10, 45, 100);
        $this->Rect(0, 0, 215, 40, 'F'); // ✅ Extended width from 210 to 215 to cover right edge perfectly

        // Logo
        $this->Image('../public/asset/images/mortarboard.png', 95, 8, 20);

        // University name
        $this->SetFont('Arial', 'B', 16);
        $this->SetTextColor(255, 255, 255);
        $this->Ln(25);
        $this->Cell(0, 5, 'UNIVERSITY OF TECHNOLOGY', 0, 1, 'C');
        $this->SetFont('Arial', '', 12);
        $this->Cell(0, 7, 'REPORT CARD', 0, 1, 'C');
        $this->Ln(8);
    }


    // Footer with date/time and text
    function Footer()
    {
        $this->SetY(-20);
        $this->SetFont('Arial', 'I', 9);
        $this->SetTextColor(128, 128, 128);

        // --- Date and time ---
        date_default_timezone_set('Africa/Mogadishu');
        $this->Cell(0, 10, 'Generated on: ' . date('d M Y, h:i A'), 0, 1, 'L');

        // --- Footer text ---
        $this->Cell(0, 10, 'Generated by Student Management System', 0, 0, 'C');
    }

    // Title section
    function SectionTitle($title) {
        $this->SetFont('Arial', 'B', 12);
        $this->SetTextColor(255, 255, 255);
        $this->SetFillColor(10, 45, 100);
        $this->Cell(0, 10, strtoupper($title), 0, 1, 'C', true);
        $this->Ln(3);
    }

    // Student info table
    function StudentInfo($student) {
        $this->SetFont('Arial', '', 11);
        $this->SetTextColor(0);
        $this->SetFillColor(240, 245, 255);

        // Two-column table for details
        $this->Cell(95, 8, 'Student Name: ' . strtoupper($student['name']), 1, 0, 'L', true);
        $this->Cell(95, 8, 'Student ID: ' . $student['id'], 1, 1, 'L', true);
        $this->Cell(95, 8, 'Email: ' . $student['email'], 1, 0, 'L', true);
        $this->Cell(95, 8, 'Phone: ' . $student['phone'], 1, 1, 'L', true);
        $this->Ln(10);
    }

function ExamsTable($exams) {
    $this->SectionTitle('STUDENT EXAMS');

    // Table header
    $this->SetFont('Arial', 'B', 10);
    $this->SetFillColor(10, 45, 100);
    $this->SetTextColor(255, 255, 255); // white text

    $this->SetX($this->lMargin);
    $this->Cell(30, 8, 'Code', 1, 0, 'C', true);
    $this->Cell(60, 8, 'Course Name', 1, 0, 'C', true);
    $this->Cell(20, 8, 'Score', 1, 0, 'C', true);
    $this->Cell(40, 8, 'Semester', 1, 0, 'C', true);
    $this->Cell(40, 8, 'Exam Date', 1, 1, 'C', true);


    // Table body
    $this->SetFont('Arial', '', 10);
    $this->SetTextColor(0); // back to black for data rows


    if ($exams->num_rows == 0) {
        $this->Cell(190, 8, 'No exams found for this student.', 1, 1, 'C');
        return;
    }

    while ($row = $exams->fetch_assoc()) {
        $this->Cell(30, 8, $row['course_code'], 1);
        $this->Cell(60, 8, $row['course_name'], 1);
        $this->Cell(20, 8, $row['score'], 1, 0, 'C');
        $this->Cell(40, 8, $row['semester'], 1);
        $this->Cell(40, 8, $row['exam_date'], 1, 1);
    }
}
}

// Fetch student info
if (isset($_GET['id'])) {
    $id = intval($_GET['id']);
    $result = $conn->query("SELECT * FROM student_info WHERE id = $id");
    $student = $result->fetch_assoc();

    $examQuery = $conn->query(
    "SELECT course_code, course_name, score, semester, exam_date 
     FROM exam_results 
     WHERE student_id = $id"
);

    $pdf = new PDF();
    $pdf->AddPage();

    // Student information section
    $pdf->SectionTitle('STUDENT INFORMATION');
    $pdf->StudentInfo($student);

    // Exams section placeholder
    $pdf->ExamsTable($examQuery);

    // Output PDF
    $filename = 'Student_Report_' . strtoupper($student['name']) . '.pdf';
    $pdf->Output('D', 'Student_Report_' . $student['name'] . '.pdf');
} else {
    echo "Student ID not provided.";
}
?>
